apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskmanager-sa
  namespace: taskmanager
  annotations:
    # This links the K8s service account to the AWS IAM role
    eks.amazonaws.com/role-arn: "arn:aws:iam::905444005978:role/taskmanager-eso-role"