apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/sivaprasad2646-group/three-tier-devops-project.git
    targetRevision: main          # Watch the main branch
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: taskmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
