apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-assistant-service-account
  namespace: taskmanager
  annotations:
    # Links the ServiceAccount to the IAM role created for the AI Assistant
    eks.amazonaws.com/role-arn: "arn:aws:iam::905444005978:role/taskmanager-ai-assistant-role"