apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: frontend
        {{- include "taskmanager.labels" . | nindent 8 }}

    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.port }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 30
            periodSeconds: 5

          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}