apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: taskdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          
          # ✅ ADD THIS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskmanager
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432